apiVersion: v1
kind: ConfigMap
metadata:
  name: oem-provider-agent-config
data:
  cx-ontology.xml: |-
{{- .Files.Get "provider/resources/cx-ontology.xml" | nindent 4 }}
  dtc.obda: |-
{{- .Files.Get "provider/resources/dtc.obda" | nindent 4 }}
  settings.properties: |-
{{- .Files.Get "provider/resources/settings.properties" | nindent 4 }}
  portal.toml: |-
{{- .Files.Get "provider/resources/portal.toml" | nindent 4 }}
---
apiVersion: v1
data:
  auth: Zm9vOiRhcHIxJEEwMVY5WUxaJGtobE9jSEowVGwvdnJBWFlUMEQ2UTAK
kind: Secret
metadata:
  name: oem-provider-auth
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oem-provider-agent
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: oem-provider-agent
  template:
    metadata:
      labels:
        app: oem-provider-agent
    spec:
      containers:
        - name: oem-provider-agent
          image: ghcr.io/catenax-ng/product-knowledge/dataspace/provisioning-agent:0.5.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # API
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
            - name: ONTOP_ONTOLOGY_FILE 
              value: "/input/cx-ontology.xml"
            - name: ONTOP_MAPPING_FILE 
              value: "/input/dtc.obda"
            - name: ONTOP_PROPERTIES_FILE
              value: "/input/settings.properties"
            - name: ONTOP_PORTAL_FILE
              value: "/input/portal.toml"
          volumeMounts:
            - name: oem-provider-agent-config
              mountPath: /input
      volumes:
        - name: oem-provider-agent-config
          configMap:
            name: oem-provider-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: oem-provider-agent
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: oem-provider-agent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oem-provider-agent-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/oem-provider-agent"
    nginx.org/mergeable-ingress-type: master
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: oem-provider-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - OEM'
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-knowledge
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /oem-provider-agent(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: oem-provider-agent
                port:
                  number: 8080