#
# Docker compose recipe for setting up the sample infrastructure
# See copyright notice in the top folder
# See authors file in the top folder
# See license file in the top folder
#

# that is the version of the docker compose runtime
version: "3.9"

services:

  #
  # Configures the provisioning agent image
  #

  provisioning-agent:
    build:
      dockerfile: Dockerfile
      context: ../dataspace/agents/provisioning
    image: ghcr.io/catenax-ng/product-knowledge/dataspace/provisioning-agent:0.5.2
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8080:8080" # sparql endpoint
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090
      ONTOP_ONTOLOGY_FILE: /input/cx-ontology.xml
      ONTOP_MAPPING_FILE: /input/dtc.obda
      ONTOP_PROPERTIES_FILE: /input/settings.properties
      ONTOP_PORTAL_FILE: /input/portal.toml
    volumes:
      - ./provider/resources/cx-ontology.xml:/input/cx-ontology.xml
      - ./provider/resources/dtc.obda:/input/dtc.obda
      - ./provider/resources/settings.properties:/input/settings.properties
      - ./provider/resources/portal.toml:/input/portal.toml
