name:  ESLint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Run ESLint
      run: |
          cd ux
          npm run init:dev
          npm run lint:report
      # Continue to the next step even if this fails
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "reports/eslint_report.json"
      continue-on-error: true
    - name: Upload ESLint report
      uses: actions/upload-artifact@v2
      with:
        name: eslint_report.json
        path: reports/eslint_report.json